name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Verify Go version
        run: go version

      - name: Install dependencies
        run: go mod download

      - name: Run tests with coverage
        run: go test ./... -coverprofile=coverage.out

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_FIAP }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=pos-tech-fiap-go-horse-1
            -Dsonar.projectKey=Pos-tech-FIAP-GO-payments-service
            -Dsonar.sources=src
            -Dsonar.go.coverage.reportPaths=coverage.out
